version: '3.8'

services:
  subway-finder:
    build: .
    container_name: realstate-poi
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: subwaydb
      NESHAN_API_KEY: service.33057ee386af4b69808a12b6ea72048e
    restart: always

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: subwaydb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: