version: '3.8'

services:
  db:
    image: postgres
    container_name: realstate-poi-database
    restart: always
    environment:
      POSTGRES_DB:  poi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
    ports:
      - "5433:5432"
    networks:
      - poi_network
    volumes:
      - db_data:/var/lib/postgresql/data



  app:
    build: .
    container_name: realstate-poi
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      ENV: prouction
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: poi
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      PORT: 8000
      KENAR_APP_SLUG: planet-ripple-legend
      KENAR_API_KEY: eyJhbGciOiJSUzI1NiIsImtpZCI6InByaXZhdGVfa2V5XzIiLCJ0eXAiOiJKV1QifQ.eyJhcHBfc2x1ZyI6InBsYW5ldC1yaXBwbGUtbGVnZW5kIiwiYXVkIjoic2VydmljZXByb3ZpZGVycyIsImV4cCI6MTc0NjM1NDM3NiwianRpIjoiNDU4YzM0MTMtZjlhYy0xMWVmLTlhMTktZmFkODI3M2I1OGM1IiwiaWF0IjoxNzQxMTcwMzc2LCJpc3MiOiJkaXZhciIsInN1YiI6ImFwaWtleSJ9.KabES1DIR9hv6FEqbQ_G2jMm06Rb3pDxcKOLNDiC67q_9uoandGrWBg1hFNBDcp7_vkgXF77If9vGdYCSgoYXbRgVtESPPYdmY8v3tpl8LiayYR4a3PA9omvpeJIGLMe_YQoL3AeyIcaf2mLf5tTuRqIunbCJxTk1fWOGe5RddwZk44g2-0uZ69tm9YUM7cqL2r8I8stgYDB8d6OWSUeXzY3NxhQK_OH09qFQyHlO0UrpY0luyWgj2RrZiA3zMQYJMJLCJSOS-Ea1a-siSIyo_5LULi2JdRkbjJsMqNNY9AkH-vn4D7knBqRPSzwBxDymLhdt9MyEf1mh6L6UFeh3A
      OAUTH_SECRET: fbe4212a8dd25c1655ac03aaecad0c39551b3fe7079bf8eb4636fcfe9eab79f5f6d71b62763107776127ee6c3a2ae6f57826226ddffebe293190ebac6c35ae32
      SESSION_AUTH_KEY: oauth-session-secret
      NESHAN_API_KEY: service.fee4f03fa6964054bd5d009dd4134ffd

      #SNAPP
      SNAPP_ACCESS_TOKEN: eyJhbGciOiJFUzI1NiIsImtpZCI6IjQ1NFFSWTV0V1N6NDlrdzJaT05JQk5vVURYUGYyQlVWWGt4SzZlUHlnakUiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOlsicGFzc2VuZ2VyIl0sImV4cCI6MTc0NDYxODA3MiwiaWF0IjoxNzQzNDA4NDcyLCJpc3MiOjEsImp0aSI6IlBwcFZqUTRIRWZDTnlGcVRlZlBsZzdRUEk3NUdyMEU0bjcxRjNCMkh2SzgiLCJxYSI6ZmFsc2UsInNpZCI6IjJ2NGRxa0xoZTJoZXFsOW9nQkpxWWphaHFHUyIsInN1YiI6InBReE81ZzlrOTZyMjRBZCJ9.qsXGoood4ivKrgicx8qhjsrrpbwQJoiiB_WICWWHUDnuPM84V4BiXrVhqCaBvQHWnJwHRBvvnffJSiMxIc-Gfg
      SNAPP_CLCK: 18lr4q0%7C2%7Cfuo%7C0%7C1916
      SNAPP_CLSK: aq9rea%7C1743420432282%7C2%7C0%7Ca.clarity.ms%2Fcollect
      SNAPP_GA: GA1.1.1797524212.1743408428
      SNAPP_GA_TRACKING: GS1.1.1743420432.3.0.1743420432.60.0.0
      SNAPP_YM_D: 1743408429
      SNAPP_YM_ISAD: 2
      SNAPP_YM_UID: 174040725793973085
      SNAPP_COOKIE_SESSION: 678B286A59DAEF11697241AFF8134934

      #TAPSI
      TAPSI_ACCESS_TOKEN: eyJraWQiOiJhY2Nlc3NfdG9rZW5fMSIsImFsZyI6IlJTMjU2In0.eyJnbG9iYWxfdXNlcl9pZCI6MzIxMDEwODQsImxvY2FsX3VzZXJfaWQiOjU4NDE2NTgwLCJzdWIiOiI1ODQxNjU4MCIsImN1c3RvbSI6e30sImlzcyI6Imh0dHBzOlwvXC9hY2NvdW50cy1hcGkudGFwc2kuaXJcL2FwaVwvdjFcL3Nzby11c2VyXC9vaWRjIiwidHlwIjoiQmVhcmVyIiwidmVyc2lvbiI6InYxIiwic2lkIjoiZWY1OGZlMDEtOGIzZi00YTdhLTgzODgtNDQ1MDZiNTIwMzk2LS1iMTQyMTU1Ny01MTU4LTQwMzEtYWQ3OS1kY2IzZDZjOTI2YjMiLCJhenAiOiJ0YXBzaS5jYWIucGFzc2VuZ2VyIiwiYXV0aF90aW1lIjoxNzQzNDE5NTY3LCJzY29wZSI6IlBBU1NFTkdFUiIsImV4cCI6MTc0NDAyNDUxNCwic2Vzc2lvbl9zdGF0ZSI6ImExNDY3MGUzYjliNzQ4MmY4Y2VhYTMxY2JlZWI0ZTg3IiwiaWF0IjoxNzQzNDE5NTY3fQ.JKU6Bl2VSSt4a5mIR5Lv-g2T3ZldvXeqI7KfzYBV54xq8hJ1SMsD82dNqd9wcD25P3yaqnSVG6E2kjUV8si364Zx0rRymaIePF_Nt9nrl6BJjno5iUCb0YTSVqgt9pfq0Pkd9IJJfKLj1ypX4ouGKd_boZW5lDIqE79kEq7lb8wfItWTdOfgtR8D6UTtu28IhJnhull9FExQ5kn_CvfThpquccw_LdfTbvkutR7SSeaIfL3OHckOJcKCFbvFuWDqNsot_fcLv6ZlV4NszKOEA_JzeAwGzUI_Weq3D0lQuCirLLAdSc0zTe3ov-DrRIEWW7SX2STiEAzVHxElgXmPPQ
      TAPSI_REFRESH_TOKEN: eyJraWQiOiJyZWZyZXNoX3Rva2VuXzEiLCJhbGciOiJSUzI1NiJ9.eyJnbG9iYWxfdXNlcl9pZCI6MzIxMDEwODQsImxvY2FsX3VzZXJfaWQiOjU4NDE2NTgwLCJzdWIiOiI1ODQxNjU4MCIsImN1c3RvbSI6e30sImlzcyI6Imh0dHBzOlwvXC9hY2NvdW50cy1hcGkudGFwc2kuaXJcL2FwaVwvdjFcL3Nzby11c2VyXC9vaWRjIiwidHlwIjoiUmVmcmVzaCIsInZlcnNpb24iOiJ2MSIsInNpZCI6ImVmNThmZTAxLThiM2YtNGE3YS04Mzg4LTQ0NTA2YjUyMDM5Ni0tYjE0MjE1NTctNTE1OC00MDMxLWFkNzktZGNiM2Q2YzkyNmIzIiwiYXVkIjoiaHR0cHM6XC9cL2FjY291bnRzLWFwaS50YXBzaS5pclwvYXBpXC92MVwvc3NvLXVzZXJcL29pZGMiLCJhenAiOiJ0YXBzaS5jYWIucGFzc2VuZ2VyIiwiYXV0aF90aW1lIjoxNzQzNDE5NTY3LCJzY29wZSI6IlBBU1NFTkdFUiIsImV4cCI6MTc1ODk3MTcxNCwic2Vzc2lvbl9zdGF0ZSI6ImExNDY3MGUzYjliNzQ4MmY4Y2VhYTMxY2JlZWI0ZTg3IiwiaWF0IjoxNzQzNDE5NTY3fQ.VwZ-Q70JgIycZUv5Ov02B2XCDiF18LvoR7CedgdNlM18GVldFrIpBnMpAPBt_az0-MS-tEQocVqDi4TQtDm8SjOtFPto4yBI4x8Dpxlfe27dIGc9GC6YLLADB4z8L2-QFyir9FtbY3252LZQ2_4lIaiw3NgHnOHJ_kJJTBIb_Z3AVZspNsk5auEEOOPSBsNU_L5X5szXaZnswDCr_gUJJK_hviafiElFU0r-NKcqqCGIxWwEX7ZircjYx1cKsDVo9cnZGOTsiGJ6FohuIbXR0YkpzltGI-0-nHdgzzCptdClTGRQY2T3jlD7MNW-vvRXVIyoKVC3s_LYaQdBy2IFMA
      TAPSI_CLCK: nq83ky%7C2%7Cfuo%7C0%7C1916
      TAPSI_CLSK: 4ptij%7C1743419757081%7C4%7C0%7Ca.clarity.ms%2Fcollect

      JWT_SECRET: Ijustwannadiebitchpls
    restart: always
    networks:
      - poi_network

  

volumes:
  db_data:

networks:
  poi_network: