apiVersion: v1
kind: Service
metadata:
  name: realestate-poi-service
spec:
  selector:
    app: realestate-poi
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  type: LoadBalancer