// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: metro_stations.sql

package db

import (
	"context"
)

const addMetroStation = `-- name: AddMetroStation :exec
INSERT INTO metro_stations (name, latitude, longitude)
VALUES ($1, $2, $3)
`

type AddMetroStationParams struct {
	Name      string  `db:"name" json:"name"`
	Latitude  float64 `db:"latitude" json:"latitude"`
	Longitude float64 `db:"longitude" json:"longitude"`
}

func (q *Queries) AddMetroStation(ctx context.Context, arg AddMetroStationParams) error {
	_, err := q.db.Exec(ctx, addMetroStation, arg.Name, arg.Latitude, arg.Longitude)
	return err
}

const getMetroStationName = `-- name: GetMetroStationName :one
SELECT name FROM metro_stations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMetroStationName(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getMetroStationName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
