// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: places.sql

package db

import (
	"context"
)

const addPlace = `-- name: AddPlace :exec
INSERT INTO places 
(name, type, latitude, longitude)
VALUES ($1, $2, $3, $4)
`

type AddPlaceParams struct {
	Name      string  `db:"name" json:"name"`
	Type      string  `db:"type" json:"type"`
	Latitude  float64 `db:"latitude" json:"latitude"`
	Longitude float64 `db:"longitude" json:"longitude"`
}

func (q *Queries) AddPlace(ctx context.Context, arg AddPlaceParams) error {
	_, err := q.db.Exec(ctx, addPlace,
		arg.Name,
		arg.Type,
		arg.Latitude,
		arg.Longitude,
	)
	return err
}
