// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: poi.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPOIResult = `-- name: AddPOIResult :exec
INSERT INTO poi (post_token, place_id, distance, duration, snapp_cost, tapsi_cost)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AddPOIResultParams struct {
	PostToken string         `db:"post_token" json:"post_token"`
	PlaceID   pgtype.Int4    `db:"place_id" json:"place_id"`
	Distance  pgtype.Numeric `db:"distance" json:"distance"`
	Duration  pgtype.Numeric `db:"duration" json:"duration"`
	SnappCost pgtype.Numeric `db:"snapp_cost" json:"snapp_cost"`
	TapsiCost pgtype.Numeric `db:"tapsi_cost" json:"tapsi_cost"`
}

func (q *Queries) AddPOIResult(ctx context.Context, arg AddPOIResultParams) error {
	_, err := q.db.Exec(ctx, addPOIResult,
		arg.PostToken,
		arg.PlaceID,
		arg.Distance,
		arg.Duration,
		arg.SnappCost,
		arg.TapsiCost,
	)
	return err
}
