// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: posts.sql

package db

import (
	"context"
)

const addPost = `-- name: AddPost :exec
INSERT INTO posts (post_token, latitude, longitude)
VALUES ($1, $2, $3)
`

type AddPostParams struct {
	PostToken string  `db:"post_token" json:"post_token"`
	Latitude  float64 `db:"latitude" json:"latitude"`
	Longitude float64 `db:"longitude" json:"longitude"`
}

func (q *Queries) AddPost(ctx context.Context, arg AddPostParams) error {
	_, err := q.db.Exec(ctx, addPost, arg.PostToken, arg.Latitude, arg.Longitude)
	return err
}
