// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	AddOAuthData(ctx context.Context, arg AddOAuthDataParams) error
	AddPOIResult(ctx context.Context, arg AddPOIResultParams) error
	AddPlace(ctx context.Context, arg AddPlaceParams) error
	AddPost(ctx context.Context, arg AddPostParams) error
}

var _ Querier = (*Queries)(nil)
