// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToken = `-- name: AddToken :exec
INSERT INTO tokens 
(user_id, user_token, post_token, user_token_expiry, post_token_expiry)
VALUES ($1, $2, $3, $4, $5)
`

type AddTokenParams struct {
	UserID          pgtype.Int4        `db:"user_id" json:"user_id"`
	UserToken       string             `db:"user_token" json:"user_token"`
	PostToken       string             `db:"post_token" json:"post_token"`
	UserTokenExpiry pgtype.Timestamptz `db:"user_token_expiry" json:"user_token_expiry"`
	PostTokenExpiry pgtype.Timestamptz `db:"post_token_expiry" json:"post_token_expiry"`
}

func (q *Queries) AddToken(ctx context.Context, arg AddTokenParams) error {
	_, err := q.db.Exec(ctx, addToken,
		arg.UserID,
		arg.UserToken,
		arg.PostToken,
		arg.UserTokenExpiry,
		arg.PostTokenExpiry,
	)
	return err
}
