// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: travel_metrics.sql

package db

import (
	"context"
)

const createTravelMetric = `-- name: CreateTravelMetric :exec
INSERT INTO travel_metrics (distance, duration,origin_id, destionation_id)
VALUES ($1, $2, $3, $4)
`

type CreateTravelMetricParams struct {
	Distance       int32  `db:"distance" json:"distance"`
	Duration       int32  `db:"duration" json:"duration"`
	OriginID       string `db:"origin_id" json:"origin_id"`
	DestionationID int32  `db:"destionation_id" json:"destionation_id"`
}

func (q *Queries) CreateTravelMetric(ctx context.Context, arg CreateTravelMetricParams) error {
	_, err := q.db.Exec(ctx, createTravelMetric,
		arg.Distance,
		arg.Duration,
		arg.OriginID,
		arg.DestionationID,
	)
	return err
}
