// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package db

import (
	"context"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id)
VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) InsertUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, insertUser, id)
	return err
}
