Database:
  Host: localhost
  Port: 5432
  DBName: poi
  Username: ${DB_USERNAME}
  Password: ${DB_PASSWORD}
  MaxConns: 5
  MinConns: 2
  MaxConnLifetimeJitterMinutes: 1
  MaxConnLifetimeMinutes: 5
  MaxConnIdleTimeMinutes: 2
  SSLMode: disable
Kenar:
  KenarAppSlug: "${KENAR_APP_SLUG}"  
  KenarApiKey: "${KENAR_API_KEY}"
  OauthSecret: "${OAUTH_SECRET}"
  BaseUrl:

Server:
  Port: "${PORT}"

Session:
  SessionAuthKey: "${SESSION_AUTH_KEY}"
  SessionEncKey:  "${SESSION_ENC_KEY}"

