Database:
  Host: localhost
  Port: 5432
  DBName: poi
  Username: postgres
  Password: postgres
  MaxConns: 5
  MinConns: 2
  MaxConnLifetimeJitterMinutes: 1
  MaxConnLifetimeMinutes: 5
  MaxConnIdleTimeMinutes: 2
  SSLMode: disable