Database:
  Host: localhost
  Port: 5432
  DBName: test-db
  Username: postgres
  Password: password
  MaxConns: 100
  MinConns: 20
  MaxConnLifetimeJitterMinutes: 1
  MaxConnLifetimeMinutes: 5
  MaxConnIdleTimeMinutes: 2
  SSLMode: allow